# -*- coding: utf-8 -*-
"""Pickle&Joblib.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11_nzeEzuqx-PPPhYdh9mdfRRnvYCdI3n
"""

import pickle
import joblib
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

df = pd.read_csv("./housing.csv").iloc[:,:-1].dropna()

X = df.drop(columns='median_house_value')
y = df['median_house_value']

print(X.shape,y.shape)

model = LinearRegression()
model.fit(X,y)

y_pred = model.predict(X)
print(y_pred)

r2_score(y,y_pred)

"""Pickle"""

with open('model.pkl','wb') as f:
  pickle.dump(model,f)

with open('model.pkl','rb') as f:
  pickle_model = pickle.load(f)

print(pickle_model)

print(pickle_model.predict(X))

"""Joblib"""

joblib.dump(model, 'joblib_model.joblib')

model_joblib = joblib.load('joblib_model.joblib')

print(model_joblib)

Y_pred = model_joblib.predict(X)

print(r2_score(y,y_pred))

